## Numpy  Basics

import numpy 

In [3]:
import numpy as np

In [5]:
#Creando un arreglo, a partir de una lsita de python
lista_python = [0,1,2,3]

mi_array = np.array( [0,1.0,2,3,5] , dtype='float' )
mi_array.dtype

dtype('float64')

In [6]:
mi_array = np.arange(0,10)
mi_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Usando métodos de cración de arreglos multidimensionales
#ones, zeros, identity, eye
mi_array = np.ones( (3,3) )
mi_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
#Qué hay dentro del objeto mi_arreglo
print ('Numero de elementos ', mi_array.size)
print ('forma dinesiones ' , mi_array.shape)
print ('Numero dimensiones ' , mi_array.ndim)
print ('Tipo de dato ' , mi_array.dtype)

Numero de elementos  9
forma dinesiones  (3, 3)
Numero dimensiones  2
Tipo de dato  float64


### Visualización de la información

In [9]:
# arreglo 2D
a = np.arange(12)

a.resize(4,3)
print (a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
# arreglo 3D
c = np.arange(24).reshape(2,3,4)
print (c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### Las operaciones básicas

In [ ]:
a = np.arange(4).reshape(2,2)
b = np.ones((2,2))
b = b + 1